config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users

  scope '/trln' do
    resources :users
    post '/users/:id/new_token', to: 'users#new_token!'
  end

  get '/dashboard' => 'dashboard#index'

  post '/dashboard/rerun', to: 'dashboard#rerun'

  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'transactions#index'

  get '/transaction/:id' => 'transactions#show'
  get '/transaction/:id/file/:filename' => 'transactions#filedownload'

  post '/transaction/:id/archive' => 'transactions#archive'

  delete '/transaction/:id' => 'transactions#destroy'

  post '/index/:id', to: 'transactions#start_index', as: 'reindex'
  post '/ingest/:owner', to: 'transactions#ingest_json', constraints: { content_type: 'application/json' }
  post '/ingest/:owner', to: 'transactions#ingest_zip', constraints: { content_type: 'application/zip' }

  get   '/ingest/:owner', to: 'transactions#ingest_form', as: 'ingest_form'
  post  '/ingest/:owner', contraints: { content_type: :multipart_form }, to: 'transactions#upload'

  get   '/record', to: 'documents#index'
  get   '/record/search', to: 'documents#search'
  get   '/record/:id' => 'documents#show', :defaults => { format: 'html'}, as: 'show_document'

  get '/nameauthority/', to: 'name_authority#index'
  get '/nameauthority/:lookup', to: 'name_authority#index'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/document.rb
require 'spofford/deepstruct'

# represents a bibliographic record
class Document < ApplicationRecord
  # need to set this explicitly
  self.primary_key = 'id'

  validates :local_id, :owner, :content, :txn, presence: true

  # "transaction" is an ActiveRecord attribute, so we have to call the
  # association something else; 'txn' is short
  belongs_to :txn, class_name: 'Transaction'
end

app/controllers/documents_controller.rb
require 'spofford'

# represents a document that is stored locally and which
# can be ingested into Solr.
class DocumentsController < ApplicationController
  include Spofford::ArgotViewer
  protect_from_forgery except: :do_post
  before_action :authenticate_user!

  def index
    @documents = Document.order(:updated_at).take(10)
  end

  def search
    logger.debug "Params: #{params[:id]}"
    begin
      @doc = Document.find(params[:id])
      logger.debug "here's the doc: #{@doc}"
      show
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Record #{params[:id]} not found"
      redirect_to(controller: 'transactions', action: 'index')
    end
  end

  def show
    @doc ||= Document.find(params[:id])
    respond_to do |format|
      format.html do
        @content = @doc.content.to_ostruct_deep
        @solr = suppress(StandardError) { fetch_solr(@doc.id) } || {}
        @enriched = suppress(StandardError) do
          prepare_for_ingest(@doc.content)
        end || {}
        @luke = suppress(StandardError) { fetch_luke_doc(@doc.id) } || {}
        if @doc.deleted?
          flash[:notice] = 'This record has been deleted.'
          if @solr.empty?
            flash[:notice] << %q{It's not currently stored in Solr}
          else
            delay = ((Time.current - @doc.updated_at) / 1.hour).round
            if delay > 1
              flash[:alert] = 'This record still appears in Solr'
            else
              flash[:notice] << "\nIt should be removed from the index soon."
            end
          end
        end
        render 'show'
      end
      format.json do
        render json: @doc.content
      end
    end
  end
end

app/helpers/documents_helper.rb
require 'json'

module DocumentsHelper
  def pretty_json(content)
    JSON.pretty_generate(content)
  end

  def main_title(content)
    return '[not present]' if content.nil?
    begin
      content.title_main.first.value
    rescue StandardError
      '[not found]'
    end
  end

  def isbns(content)
    return '' if content.nil?
    return '' if content.try(:isbn).nil?
    begin
      content.isbn.map do |isbn|
        isbn.number + ( isbn.qualifying_info ? " #{isbn.qualifying_info}" : '' )
      end.join(', ')
    rescue StandardError
      '[unable to retrieve]'
    end
  end
end

app/views/documents/index.html.erb
<% content_for :title do %>
 TRLN Shared Record Index Management
<% end %> 
<h1><%= yield(:title) %></h1>
  <ul>
 <% @documents.each do |doc| %>
    <li><%= link_to(doc.id, show_document_url(doc) ) %></li>
        <% end %>
  </ul>

app/views/documents/show.html.erb
<%= content_for(:title, "TRLN Record : #{@doc.id}") %>
<div class="main">
  <div class="header <%= @doc.owner %>">
      <h1>ID: <%= @doc.id %><% if @doc.deleted? %>
      <span class='deleted'>( deleted )</span><% end %></h1>
  </div>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title"><%= link_to( "View Transaction", @doc.txn, class: 'btn btn-primary text-white') %></h3>
      </div>
    </div>

  <div class="card metadata bibliographic">

    <div class="card-body">
      <h3 class="card-title"><%= main_title(@content) %></h3>
      <h5 class="card-subtitle mb-2 text-muted">Last Updated: <%= @doc.updated_at.in_time_zone.strftime("%a, %b %d, %Y @ %I:%M %P") %> (<%= @doc.updated_at.in_time_zone %>)</h5>
      <h5 class="card-subtitle mb-2 text-muted">Source: <%= @content.record_data_source&.join(',') %></h5>
	<% if @content.rollup_id %>
      <h5 class="card-subtitle mb-2 text-muted">Rollup ID: <%= @content.rollup_id %></h5>
	<% end %>
      <h5 class="card-subtitle mb-2 text-muted">Availability: <%= @content.available || '(not avaialable)' %></h5>

     <% if @content.items %>
	<h6 class="card-subtitle text-muted"><%= pluralize(@content.items.length, 'item') %></h6>
     <% end %>

    <div class="basic-props">

     <dl>
	<dt>Access Type</dt>
	<% @content.access_type&.each do |t| %>
	  <dd><%= t %>
	<% end %> 
	</dl>
     <dl>
	<dt>Resource Type</dt>
	<% @content.resource_type&.each do |t| %>
	  <dd><%= t %>
	<% end %>
     </dl>
<dl>
	<dt>Physical Media</dt>
	<% @content.physical_media&.each do |pm| %>
	  <dd><%= pm %></dd>
	<% end %>
	</dl>
	<dl>
	
	<dt><%= 'Institution'.pluralize(@content.institution&.length) %></dt>
	<% @content.institution&.each do |i| %>
          <dd><%= i %></dd>
	<% end %>
     </dl>

    <% if @content.virtual_collection && @content.virtual_collection.try(:first) %>
      <dl>
        <dt>Virtual <%= 'Collection'.pluralize(@content.virtual_collection.length,) %></dt>
          <% @content.virtual_collection&.each do |coll| %>
        <dd><%= coll %></dd>
        <% end %>
      </dl>
      <% end %>
  
	
  </div>



    </div>
  </div>
 
  <div class="card" id="argot-views">
    <div class="card-body">
      <h3 class="card-title">Document Views</h3>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#argot" aria-expanded="true" aria-controls="argot">
      <span class='visible'>Hide</span>
      <span class='hidden'>Show</span>
      Argot
    </button>
  </li>
      <li class="list-group-item">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#enriched-view" aria-expanded="false" aria-controls="enriched-view">
      <span class='visible'>Hide</span>
      <span class='hidden'>Show</span>
      Enriched Argot (what Solr ingests)
    </button>
  </li>
        <li class="list-group-item">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#solr-view" aria-expanded="false" aria-controls="solr-view">
      <span class='visible'>Hide</span>
      <span class='hidden'>Show</span>
      Solr Document
    </button></li>

    <li class="list-group-item">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="argot enriched-view solr-view luke-view">
     <span class='visible'>Hide</span>
      <span class='hidden'>Show</span>
      All
    </button>
  </li>

    <div id="argot" class="collapse multi-collapse show">
      <h3>Argot (<%= link_to('download', controller: 'documents', action: 'show', id: @doc.id, format: :json) %>)</h3>
      <span class='detail'>Currently Stored</span>
      <code><pre><%= pretty_json(@doc.content) %></pre></code>
    </div>
  
  </div>

    <div id="enriched-view" class="collapse multi-collapse">
      <h3>Enriched Content (what gets sent to Solr)</h3>
      <span class="detail">Generated at Indexing time</span>
      <code><pre><%= pretty_json(@enriched) %></pre></code>
    </div>
    

    <div id="solr-view" class="collapse multi-collapse">
      <h1>Current Solr Content</h1>
      <span class='detail'>Data currently in shared index</span>
        <code><pre><%= pretty_json(@solr) %></pre></code>
      </div>
    </div>
  </div>
</div>