config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users

  scope '/trln' do
    resources :users
    post '/users/:id/new_token', to: 'users#new_token!'
  end

  get '/dashboard' => 'dashboard#index'

  post '/dashboard/rerun', to: 'dashboard#rerun'

  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'transactions#index'

  get '/transaction/:id' => 'transactions#show'
  get '/transaction/:id/file/:filename' => 'transactions#filedownload'

  post '/transaction/:id/archive' => 'transactions#archive'

  delete '/transaction/:id' => 'transactions#destroy'

  post '/index/:id', to: 'transactions#start_index', as: 'reindex'
  post '/ingest/:owner', to: 'transactions#ingest_json', constraints: { content_type: 'application/json' }
  post '/ingest/:owner', to: 'transactions#ingest_zip', constraints: { content_type: 'application/zip' }

  get   '/ingest/:owner', to: 'transactions#ingest_form', as: 'ingest_form'
  post  '/ingest/:owner', contraints: { content_type: :multipart_form }, to: 'transactions#upload'

  get   '/record', to: 'documents#index'
  get   '/record/search', to: 'documents#search'
  get   '/record/:id' => 'documents#show', :defaults => { format: 'html'}, as: 'show_document'

  get '/nameauthority/', to: 'name_authority#index'
  get '/nameauthority/:lookup', to: 'name_authority#index'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/transactions_controller.rb
# Controller for managing transactions
class TransactionsController < ApplicationController
  include Spofford::IngestHelper

  protect_from_forgery except: %i[ingest_json ingest_zip]
  acts_as_token_authentication_handler_for User, only: %i[index show ingest_zip ingest_json], fallback: :exception

  before_action :authenticate_user!
  before_action :set_transaction, only: %i[show edit update destroy archive]

  # GET /transactions
  # GET /transactions.json
  def index
    filters = { owner: current_user.primary_institution }
    filters = {} if params[:view] == 'all'
    @transactions = Transaction.where(filters).page(params[:page]).order('created_at DESC')
    @filtered = !filters.empty?
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @document_ids = Document.where(txn: @transaction).select(:id, :local_id)
    @job_status = helpers.sidekiq_job_status(@transaction.id)
    @zip_entries = Hash[@transaction.files.select { |f| File.exist?(f) && File.extname(f) == '.zip' }
                               .map { |f| [f, helpers.zip_contents(f)] }]
  end

  # GET /transactions/:id/edit
  def edit
    start_worker
  end

  def archive
    @transaction.archive!
  end

  # POST /ingest/:owner ( application/zip )
  def ingest_zip
    if request.body.size.zero?
      logger.info("#{params[:owner]} -- received empty body")
      return render(text: 'No content uploaded', status: 400)
    end
    @owner = params[:owner].downcase
    begin
      accept_zip(request.body, @owner) do |files|
        @transaction = Transaction.new(owner: @owner, user: current_user, files: files)
        @transaction.stash!
        @transaction.save!
      end
      start_worker
    rescue ArgumentError => e
      render status: 400, json: { status: 'JSON error', message: e.message }
    rescue StandardError => e
      render status: 500, json: { status: 'Unknown error', message: e.message }
    end
  end

  # POST /ingest/:owner ( application/json )
  def ingest_json
    @owner = params[:owner].downcase
    if request.body.size.zero?
      logger.info 'Received empty body'
      return render(text: 'No content uploaded', status: 400)
    end
    files = [accept_json(request.body, @owner, operation: 'add')]
    begin
      @transaction = Transaction.create(owner: @owner, files: files, user: current_user)
      @transaction.stash!
      @transaction.save!
      start_worker
    rescue ArgumentError => e
      render status: 400, json: { status: 'JSON error', message: e.message }
    rescue StandardError => e
      render status: 500, json: { status: 'Unknown error', message: e.message }
    end
  end

  # POST /ingest/:owner w/ multipart mime type
  def upload
    @owner = params[:owner]
    @package = params[:package]
  end

  # GET :id/filedownload/:filename
  def filedownload
    @transaction = Transaction.find(params[:id])
    name = helpers.filename_for_download
    path = helpers.path_for_download(name)
    return render(text: 'File not found', status: 404) unless File.exist?(path)
    type = helpers.mime_type_from_filename(name)
    type ||= request.format
    # our 'json' files are streaming format, which breaks most browser
    # parsers, so force download
    send_file(path, filename: name, disposition: 'attachment', type: type)
  end

  def ingest_form
    @owner = params[:owner]
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /transactions/1/index
  def start_index
    @transaction = Transaction.find(params[:id])
    IndexingWorker.perform_async(@transaction.id)
    show
  end

  private

  def start_worker
    TransactionWorker.perform_async(@transaction.id)
    response.status = :accepted
    render 'ingest'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    raise ActionController::RoutingError, 'Not Found'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transaction_params
    params.permit(:view)
    params.require(:transaction).permit(:owner, :user, :status, :files)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  STATUS_LABELS = {
    'Ingesting' => {
      label_class: 'warning',
      text: 'Loading records into database',
    },
    'Indexing' => {
      label_class: 'info',
      text: 'Transforming and loading records into Solr',
    },
    'Archived' => {
      label_class: 'secondary',
      text:  'complete, files are compressed and ready for cold storage'
    },
    'Complete' => {
      label_class: 'primary',
      text: 'All (valid) documents have been stored and loaded into Solr'
    }
  }.freeze

  def filename_for_download
    name = File.basename(params[:filename])
    name += '.json' if request.format.symbol == :json
    name
  end

  def path_for_download(name)
    if @transaction.status == 'Archived'
      @transaction.files[0]
    else
      File.join(File.join(@transaction.stash_directory, name))
    end
  end

  def mime_type_from_filename(name)
    return nil unless name
    ext = File.extname(name)[1..-1]
    Mime::Type.lookup_by_extension(ext)
  end

  def sidekiq_job_status(id)
    tx_workers = %w[IndexingWorker TransactionWorker]
    Sidekiq::Workers.new.each do |_pid, _thread, wk|
      payload = wk['payload']
      if payload['args'] == [id] && tx_workers.include?(payload['class'])
        return 'Running'
      end
    end

    Sidekiq::RetrySet.new.select do |job|
      next unless tx_workers.include?(job.klass.to_s)
      return 'Retrying' if job.args == [id]
    end
    'Done'
  end

  def zip_contents(zipfile)
    File.open(zipfile) do |f|
      Zip::File.open(f) do |zip|
        zip.entries.map do |e|
          { name: e.name, size: e.size }
        end
      end
    end
  rescue IOError
    []
  end

  def status_label_class(txn)
    STATUS_LABELS.fetch(txn.status, label_class: 'danger')[:label_class]
  end

  def status_description(txn)
    STATUS_LABELS.fetch(txn.status, text: 'Unknown')[:text]
  end
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Owner' %>
    <%= f.text_field :owner %>
  </div>

  <div class="field">
    <%= f.label 'User' %>
    <%= f.text_field :user %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :files %>
    <%= f.text_field :files %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_show_documents.erb
 <div class="card">
  <div class="card-body">
      <label for="nosubmit">View Records</label>
      <input list="document_ids" name='nosubmit' id='nosubmit' placeholder="record unique ID" onchange='window.location="<%= url_for(controller:'documents', trailing_slash: 1) %>" + this.value;'>
      <datalist id='document_ids'>
        <% @document_ids.each do |did| %>
        <option value='<%= did.id %>' />
        <% end %>
      </datalist>
    </div>
  </div>

app/views/transactions/_show_files.erb
<div class="card">
   <div class="card-body">
    <h3 class="card-title">Files</h3>
    <ul class="list-group list-group-flush">
     <% @transaction.files.each do |f| %>

      <li class="list-group-item"><%if  File.exist?(f) %>
        <%= link_to(File.basename(f), controller: 'transactions', action: 'filedownload', id: @transaction.id, filename: File.basename(f) ) %> 
          <%= number_to_human_size(File.size(f)) %>
          <% if @zip_entries[f] %>
            <span class="badge badge-info">Zip contents</span>
            <ul>
              <% @zip_entries[f].each do |e| %>
               <li>
                <%= File.basename(e[:name]) %> <%= number_to_human_size(e[:size]) %>
              </li>
              <% end %>
            </ul>
          <% end %>
        <% else %>
         <%= File.basename(f) %> '(missing)'
         <% end %>
       </li>
     <% end %>
   </ul>
 </div>
</div>

<% unless @transaction.error_files.empty? %>
<div class="card">
  <div class="card-body">
    <h3 class="card-title">Errors</h3>
    <h4 class="card-subtitle text-muted">Not all records that were sumbitted could be ingested</h4>
  
  <ul class="list-group list-group-flush">
    <% @transaction.record_errors.each do |err| %>
      <li class="list-group-item">[ <%= err['id'] %> ] : <%= err['msg'] %></li>
    <% end %>
  </ul>
  </div>
</div>
 <% end %>

app/views/transactions/_show_nodocs.erb
<div class="card">
   <div class="card-body">
    <h4 class="card-title">Empty Batch</h4>
    <h5 class="card-subtitle text-muted">There are currently no records associated with this batch, probably because:</h5>
    <ul>
	  <% if @transaction.status == 'Ingesting' %>
	   <li class="text-notice">Ingest is still ongoing</li>
	  <% elsif ['Archived', 'Complete'].include?(@transaction.status) %>
	   <li class="text-notice">the records have all been updated since it was initially submitted, <strong>OR</strong></li>
     <li class="text-notice">they all had errors that prevented ingest.</li>
   	<% else %>
   	  <li class="text-warning">... we're not sure, really.</li>
   	<% end %>
    </ul>
  </div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<%= content_for(:title, "TRLN Ingest: Recent Updates") %>


<div class="alert alert-secondary" role="alert">
<% if @filtered %> 
  Viewing transactions only from your primary institution.
    <%= link_to("See all transactions", '/?view=all', class: "alert-link" ) %>
  <% else %>
     Viewing transactions from all institutions.
   <%= link_to("See only your institution's transactions", '/', class: "alert-link") %>
    
<% end %>
</div>

<table class="table transactions">
  <thead>
    <tr>
      <th>Owner</th>
      <th>Time</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @transactions.each do |transaction| %>
      <tr class="transaction">
        <td class='owner <%= transaction.owner.downcase %>'><%= transaction.owner.upcase %></td>
        <td><%= local_time transaction.created_at %> <br />
          (<%= time_ago_in_words transaction.created_at %> ago)</td>
        <td><%= transaction.user ? transaction.user.username : '<nope>' %></td>
        <td><%= transaction.status %></td>
        <td><%= link_to 'View', transaction, class: 'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
       <td colspan='5'>
      <%= paginate @transactions %>
    </td>
    </tr>
    <tr>
      <td colspan='5'>
        <%= page_entries_info(@transactions) %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/transactions/ingest.html.erb
<% content_for :title do %>
Spofford - TRLN Ingest Results
<% end %> 
<h1><%= yield(:title) %></h1>
 <p>Transaction ID: <%= @transaction.id %>
 <p>Owner: <%= @transaction.owner %>
 <p>Files:
   <ul>
     <% @transaction.files.each do |f|  %>
        <li><%= f %></li>
     <% end %>
  </ul>
 

app/views/transactions/ingest_form.html.erb
<% content_for(:title, "Ingest Form: #{@owner }") %>
<div class="ingest <%= @owner.downcase %>">
<h1><%= yield(:title) %></h1>
<%= form_for( :upload, { :owner => @owner.downcase, :html => { :multipart => true} }) do |f| %>
	<%= f.file_field :package %>
	<br />
	<%= f.submit %>
<% end %>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<%= content_for(:title, "TRLN Ingest Package : #{@transaction.id}") %>
<div class="transaction header <%= @transaction.owner.downcase %>">
  <h1><%= @transaction.owner.upcase %></h1>
  <h3>Tag: <%= @transaction.tag %></h3>
  <h4>Documents: <span><%= @document_ids.length || 0 %></span></h4>
</div>

<div class="row">
  <div class="col-sm-12">
  <div class="card center">
    <div class="card-header">
        Initiator: <%= @transaction.user.username || "unknown" %> at <span class="text-muted"><%= local_time @transaction.created_at %></span>
        Status: <span class="badge badge-<%= status_label_class(@transaction) %>"><%= @transaction.status || "(??)" %></span>
      </div>
      <div class="card-body">
          <h3 class="text-muted"><%= status_description(@transaction) %></h3>
          <% unless @document_ids.empty? %>
          <hr>
          <%= render "show_documents" %>
          <hr>
      <div class="txn-actions">
        <% if %w[Complete Indexing].include?(@transaction.status) %>
          <% if @transaction.status == 'Indexing' %>
            <p class="text-warning">Current status is 'Indexing', which may mean another indexing process
              is already running.  It would be a bad idea to reindex if so.  Only click this button if you're
                sure.
            </p>
          <% else %>
            <%= form_for @transaction, url: url_for(action: 'archive'), method: :post do |f| %>
                  <% f.submit 'Archive', class: 'btn btn-outline-secondary', title: 'compacts the files' %>
                <% end %>
          <% end %>
          <%= form_for @transaction, :url => url_for(:action => 'start_index'), :method => :post do |f| %> 
            <% f.submit 'Reindex', class: 'btn btn-outline-warning' %>
          <% end %>
      <% end %>
      </div>
    <% else %>
      <%= render partial: "show_nodocs" %>
    <% end %>
        </div>
    </div>
  </div>
</div>

 
 <%= render "show_files" %>


<%= link_to 'Back', transactions_path %>